backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"     # where uploaded images go in repo
public_folder: "/images/uploads"   # public URL path

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Product Name"
        name: "title"
        widget: "string"

      - label: "Price (in ₹)"
        name: "price"
        widget: "number"
        min: 0
        step: 1

      - label: "Product Image"
        name: "image"
        widget: "image"

      - label: "Description"
        name: "description"
        widget: "text"
